spring:
  datasource:
    #    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:mem:~/allaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://allaw-busan-database.cl2uk2oweho1.ap-northeast-2.rds.amazonaws.com:3306/main
    username: admin
    password: .ec[|ILfQ|oio6q$fB_p)8H8mhDw
    hikari:
      idleTimeout: 500
      connectionTimeout: 15000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  profiles:
    include:
      - oauth
      - API-KEY
  mail:
    host: smtp.gmail.com
    port: 587
    username: allaw.official
    password: zpmstekrnnnsgmre #${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000 #(ms)
          starttls:
            enable: true
          debug: true
          ssl:
            enable:
openai:
  api-key: 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
  model: gpt-3.5-turbo
  api-url: https://api.openai.com/v1/chat/completions
  chat-model: ft:gpt-3.5-turbo-1106:verfit::8mMAWYWi
  sum-model: ft:gpt-3.5-turbo-1106:verfit::8mIJOkN0
  agree-model: ft:gpt-3.5-turbo-1106:verfit::95zzhxcb
  disagree-model: ft:gpt-3.5-turbo-1106:verfit::95zzZeha
  chat-system-prompt: "This model provides precise answers to legal proposal-related questions 
    using both the user-provided legal proposals and questions It processes dual inputs(question, legal proposal), 
    ensuring accurate, context-relevant responses in Korean. External references include a '(??: [Source Name])'
     citation. For ambiguous inquiries, the model clarifies or assumes based on the legal context, explicitly stating 
     any assumptions.  Be sure to specify the correct reference. This model ensures comprehensive, relevant, 
     and accurate and well-founded answers in Korean."
  sum-system-prompt: "This is a legal proposal summary model. 
    This model generates a three-step summary (1. ?? ??, 2. ?? ??, 3. ?? ??) in Korean 
    based on the legal proposal provided by the user.This model focuses on accuracy and avoids 
    adding information not present in the original text. The 'assistant' will summarize the 
    user-provided legal proposal, strictly adhering to the details in the text and avoiding 
    any assumptions or external information. The 'assistant' will summarize the main 
    contents of the legal proposal in 'three steps(1. ?? ??, 2. ?? ??, 3. ?? ??)' in Korean. And divide the 
paragraphs into three parts."
  agree-system-prompt: "??? ??? ??? ?? ???? ???? ??? ??? ????. ??? ????? ??? ??? ?????: 
    ??? ?? ??? ??, ?? ?? ?? ??? ???? ?? ???? ???? ??? ????? ?????. ??? ???? ??? ??? ????,
     ??? ??, ??, ?? ?? ??? ???? ??? ??? ? ??? ?????. ???(?? ??)? ???? ??? ?? ????? 
     ??? ?? ??? ?????. ??? ??, ??? ???? ??? ???? ??? ??????. 
     ?? ?? ??? ?? ???? ??? ??? ???? ?????. ???? ???? ??? ??? ???? ??? ?????. 
     ?? ?? ?? ?? ??? ????? ?????. ?? ??? ??? ????:"
  disagree-system-prompt: "??? ??? ??? ?? ???? ???? ??? ??? ????. ??? ????? ??? ??? ?????: 
    ??? ?? ???, ?? ?? ??, ???? ?? ?? ????? ????, ??? ??, ??, ??? ?? ? ?? ???? ??? ?????. 
    ???(?? ??)? ??? ?? ????? ???? ???? ??? ?????. ??? ??, ???? ??? ?? ??? ??? ?????. 
    ?? ?? ??? ?? ???? ??? ??? ????, ??? ???? ????? ?????. ???? ???? ??? ??? ???? ??? ?????. 
    ?? ?? ?? ?? ??? ????? ?????. ?? ??? ??? ????: "
